export const SKIN_PRODUCT_LIST = [
    {
        id: 1,
        image: '/images/bottleSecond100mL.png',
        name: '리무브',
        volume: '60 mL',
        price: 27000,
        skinType: '모든 피부, 메이크업을 한 피부',
        texture: '진정된, 생기있는',
    },
    {
        id: 2,
        image: '/images/bottle200mL.png',
        name: '이름파슬리 씨드 오일',
        volume: '200 mL',
        price: 65000,
        skinType: '중성, 복합성, 건성, 민감성 피부',
        texture: '부드러운, 진정된',
    },
    {
        id: 3,
        image: '/images/tube100mL.png',
        name: '퓨리파잉 클렌저',
        volume: '100 mL',
        price: 40000,
        skinType: '중성, 건성 피부',
        texture: '탄력, 유연, 부드러운',
    },
    {
        id: 4,
        image: '/images/bottle100mL.png',
        name: '페뷸러스 페이스 클렌저',
        volume: '100 mL',
        price: 35000,
        skinType: '중성, 건성 피부',
        texture: '상쾌한, 진정된, 부드러운',
    },
    {
        id: 5,
        image: '/images/bottle100mL.png',
        name: '파슬리 씨드 페이셜 클렌저',
        volume: '100 mL',
        price: 45000,
        skinType: '중성, 복합성, 문제성 피부',
        texture: '매끄러운, 부드러운',
    },
    {
        id: 6,
        image: '/images/bottle100mL.png',
        name: '어메이징 페이스 클렌저',
        volume: '100 mL',
        price: 35000,
        skinType: '지성, 복합성 피부, 덥고 습한 날씨의 피부',
        texture: '산뜻한, 매끄러운',
    },
];
